Repository EOSIO/welcome, pull requests merged in 2020-02, with the labels that each got.

#137 Fixed broken links. Removed inaccurate description
  docs/02_getting-started/02_development-environment/03_before-you-begin.md
  docs/02_getting-started/02_development-environment/06_start-your-node-setup.md
  docs/02_getting-started/02_development-environment/07_create-test-accounts.md
  docs/02_getting-started/03_smart-contract-development/02_deploy-issue-and-transfer-tokens.md
Labels: broken link, inaccurate

#127 Categorize items in resource-directory.yaml
  docs/02_getting-started/02_development-environment/02_introduction.md
  resource-directory.yaml
Labels: formatting

#138 Updated image file name
  docs/09_get-involved/index.md
Labels: broken link

#118 Editorial updates to glossary terms
  docs/03_tutorials/bios-boot-sequence.md
  docs/09_get-involved/index.md
  glossary.yaml
Labels: enhancement, formatting, syntax

#150 Fix link in bios boot tutorial
  docs/03_tutorials/bios-boot-sequence.md
Labels: broken link

#151 Added tools to the list
  manuals-directory.yaml
Labels: missing

#154 Editorial and peer review
  docs/03_tutorials/monitoring-with-3rd-party-plugins.md
Labels: Peer review

#155 add chain controller signals
  docs/04_protocol/03_network_peer_protocol.md
Labels: doc debt, enhancement, missing
