Repository EOSIO/welcome, pull requests merged in 2020-03, with the labels that each got.

#159 Apply markdown syntax to 3rd party monitoring
  docs/03_tutorials/monitoring-with-3rd-party-plugins.md
Labels: formatting

#144 Add a troubleshooting note for starting keosd
  docs/02_getting-started/02_development-environment/06_start-your-node-setup.md
Labels: enhancement

#166 getting started vs get started
  docs/02_getting-started/01_try-eosio.md
  docs/02_getting-started/index.md
  docs/index.md
Labels: enhancement

#163 EOSIO Community Tools List
  docs.json
  docs/05_community-developer-tools/index.md
Labels: new document

#165 Removed redundancy in glossary.yaml
  glossary.yaml
Labels: formatting

#174 Update 02_transactions_protocol.md
  docs/04_protocol/02_transactions_protocol.md
Labels: docs, typo
